#ifndef LAYER_3_H
#define LAYER_3_H

#include "main.h"

LayoutKey layer3Layout[rowsCount][columnsCount] = {
  {{KEY_NULL},{KEY_F1},  {KEY_F2},  {KEY_F3},  {KEY_F4},        {KEY_F5},               {KEY_F6},                {KEY_F7},         {KEY_F8},  {KEY_F9},  {KEY_F10}, {KEY_F11}, {KEY_F12},  {KEY_NULL},{KEY_NULL}},
  {{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_LEFT_BRACE},{KEY_SYMBOL_LEFT_BRACE},{KEY_SYMBOL_RIGHT_BRACE},{KEY_RIGHT_BRACE},{KEY_NULL},{KEY_NULL},{KEY_PLUS},{KEY_NULL},{KEY_NULL}, {KEY_NULL},{KEY_NULL}},
  {{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},      {KEY_LEFT_PARENTHESIS}, {KEY_RIGHT_PARENTHESIS}, {KEY_NULL},       {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_ENTER},{KEY_NULL},{KEY_NULL}},
  {{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},      {KEY_LEFT_CHEVRON},     {KEY_RIGHT_CHEVRON},     {KEY_NULL},       {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL}, {KEY_NULL},{KEY_NULL}},
  {{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},      {KEY_ENTER},            {KEY_DELETE},            {LAYER_3},        {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL}, {KEY_NULL},{KEY_NULL}}
};

#endif
