#ifndef LAYER_5_H
#define LAYER_5_H

#include "main.h"

LayoutKey layout5[rowsCount][columnsCount] = {
  {{KEY_REBOOT},{KEY_GM1}, {KEY_NULL},{KEY_NULL},{KEY_NULL},  {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},      {KEY_NULL},{KEY_PRINTSCREEN},{KEY_NUM_LOCK}},
  {{KEY_NULL},  {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},  {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},      {KEY_NULL},{KEY_PAUSE},      {KEY_SCROLL_LOCK}},
  {{KEY_NULL},  {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},  {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},      {KEY_NULL},{KEY_REC},        {KEY_VOL_UP_5}},
  {{KEY_NULL},  {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},  {KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_RW},  {KEY_FF},        {KEY_NULL},{KEY_VOL_UP},     {KEY_VOL_DOWN_5}},
  {{KEY_SET0},  {KEY_NULL},{KEY_NULL},{KEY_NULL},{LAYER_GAME},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_NULL},{KEY_MUTE},{LAYER_5}, {KEY_PLAY_PAUSE},{KEY_PREV},{KEY_VOL_DOWN},   {KEY_NEXT}}
};

#endif
